# Generated by Django 5.2.9 on 2026-01-28 18:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_service", "0002_apiratelimit_endpoint_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="apiendpoint",
            name="timeout",
            field=models.IntegerField(
                blank=True,
                help_text="Tiempo de espera máximo en segundos para las peticiones a este endpoint",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(300),
                ],
            ),
        ),
    ]
