# Generated by Django 5.2.9 on 2026-01-28 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_service", "0003_apiendpoint_timeout"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apiratelimit",
            name="service",
            field=models.ForeignKey(
                help_text="Servicio API monitoreado",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rate_limits",
                to="api_service.apiservice",
            ),
        ),
    ]
