# Generated by Django 5.2.9 on 2026-02-18 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_service", "0004_alter_apiratelimit_service"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apicalllog",
            name="error_message",
            field=models.TextField(
                blank=True, help_text="Mensaje de error en caso de fallo", null=True
            ),
        ),
    ]
