# Generated by Django 5.2.7 on 2025-11-13 22:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Razón Social o Nombre Comercial')),
                ('vat', models.CharField(max_length=11, unique=True, verbose_name='RUC')),
                ('sequence', models.CharField(max_length=64, verbose_name='Secuencia de Documentos')),
                ('report_header', models.TextField(blank=True, null=True, verbose_name='Encabezado de Reportes')),
                ('report_footer', models.TextField(blank=True, null=True, verbose_name='Pie de Página de Reportes')),
                ('logo_web', models.ImageField(blank=True, null=True, upload_to='company/logos/', verbose_name='Logo para Web')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3, unique=True, verbose_name='Código de Moneda')),
                ('symbol', models.CharField(max_length=5, verbose_name='Símbolo de Moneda')),
                ('decimal_places', models.IntegerField(default=2, verbose_name='Decimales de Redondeo')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('pse_code', models.CharField(max_length=3, verbose_name='Código PSE')),
                ('singular_name', models.CharField(max_length=64, verbose_name='Nombre Singular')),
                ('plural_name', models.CharField(max_length=64, verbose_name='Nombre Plural')),
                ('fraction_name', models.CharField(max_length=64, verbose_name='Nombre de la Fracción')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('defaultcode', models.CharField(max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=6, max_digits=18, verbose_name='Tasa de Cambio')),
                ('date_rate', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de la Tasa')),
                ('purchase_rate', models.DecimalField(decimal_places=6, default=0, max_digits=18, verbose_name='Tasa de Compra')),
                ('sale_rate', models.DecimalField(decimal_places=6, default=0, max_digits=18, verbose_name='Tasa de Venta')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.company', verbose_name='Compañía')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.currency', verbose_name='Moneda')),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=50)),
                ('sequence', models.CharField(max_length=64)),
                ('voucher_edit', models.BooleanField(default=False)),
                ('check_surrender', models.BooleanField(default=False)),
                ('check_manual_sequencing', models.BooleanField(default=False)),
                ('bank_position', models.CharField(max_length=50)),
                ('is_factoring', models.BooleanField(default=False)),
                ('refund_sequence', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.company')),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nombre o Razón Social')),
                ('display_name', models.CharField(max_length=255, verbose_name='Nombre para Mostrar')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('email_secondary', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico Secundario')),
                ('vat', models.CharField(max_length=11, unique=True, verbose_name='RUC o DNI')),
                ('num_document', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Número de Documento')),
                ('ref', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Referencia Interna')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Sitio Web')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Notas Adicionales')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_foreign', models.BooleanField(default=False, verbose_name='Es Extranjero')),
                ('is_employee', models.BooleanField(default=False, verbose_name='Es Empleado')),
                ('is_supplier', models.BooleanField(default=False, verbose_name='Es Proveedor')),
                ('is_customer', models.BooleanField(default=True, verbose_name='Es Cliente')),
                ('is_company', models.BooleanField(default=False, verbose_name='Es Empresa')),
                ('is_detractor', models.BooleanField(default=False, verbose_name='Sujeto a Detracción')),
                ('is_partner_retention', models.BooleanField(default=False, verbose_name='Sujeto a Retención')),
                ('street', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('street2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección 2')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('mobile', models.CharField(blank=True, max_length=20, null=True, verbose_name='Móvil')),
                ('ruc_state', models.CharField(blank=True, max_length=3, null=True, verbose_name='Estado RUC')),
                ('ruc_condition', models.CharField(blank=True, max_length=3, null=True, verbose_name='Condición RUC')),
                ('sunat_success', models.BooleanField(default=False, verbose_name='SUNAT Exitosa')),
                ('sunat_state', models.CharField(blank=True, max_length=3, null=True, verbose_name='Estado SUNAT')),
                ('sunat_condition', models.CharField(blank=True, max_length=3, null=True, verbose_name='Condición SUNAT')),
                ('partner_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitud')),
                ('partner_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitud')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='billing.partner', verbose_name='Empresa Relacionada')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partners', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Asociado')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='company',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.partner', verbose_name='Partner Asociado'),
        ),
        migrations.CreateModel(
            name='SaleSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField(blank=True, null=True)),
                ('recurring_invoice_count', models.IntegerField(default=0)),
                ('recurring_invoice_day', models.IntegerField(default=1)),
                ('recurring_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('recurring_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('state', models.CharField(default='active', max_length=20)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('uuid', models.CharField(max_length=64, unique=True)),
                ('health', models.CharField(default='normal', max_length=20)),
                ('to_renew', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.company')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.partner')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccountMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('date_invoice', models.DateField(default=django.utils.timezone.now)),
                ('state', models.CharField(default='draft', max_length=20)),
                ('amount_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('invoice_origin', models.CharField(blank=True, max_length=128, null=True)),
                ('pdf_attachment', models.FileField(blank=True, null=True, upload_to='invoices/pdf/')),
                ('xml_attachment', models.FileField(blank=True, null=True, upload_to='invoices/xml/')),
                ('qr_code_url', models.URLField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.company')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.journal')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.partner')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.salesubscription')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type_tax_use', models.CharField(max_length=50)),
                ('amount_type', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('sequence', models.CharField(max_length=64)),
                ('amount', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('price_include', models.BooleanField(default=False)),
                ('include_base_amount', models.BooleanField(default=False)),
                ('code_fe', models.CharField(blank=True, max_length=10, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.company')),
            ],
        ),
        migrations.CreateModel(
            name='SaleSubscriptionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_unit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.product')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='billing.salesubscription')),
                ('tax_ids', models.ManyToManyField(blank=True, to='billing.tax')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccountMoveLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_unit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('move', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='billing.accountmove')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.product')),
                ('tax_ids', models.ManyToManyField(blank=True, to='billing.tax')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
