# Generated by Django 5.2.7 on 2025-11-14 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_remove_partner_vat_company_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='account_tax_periodicity',
            field=models.CharField(choices=[('monthly', 'Mensual'), ('quarterly', 'Trimestral'), ('biannual', 'Semestral'), ('annual', 'Anual')], default='monthly', max_length=20, verbose_name='Periodicidad de Declaración de Impuestos'),
        ),
        migrations.AddField(
            model_name='company',
            name='account_tax_periodicity_reminder_day',
            field=models.IntegerField(default=7, verbose_name='Día de Recordatorio de Periodicidad de Impuestos'),
        ),
        migrations.AddField(
            model_name='company',
            name='bank_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comentario Bancario'),
        ),
        migrations.AddField(
            model_name='company',
            name='company_color',
            field=models.CharField(default='blue', max_length=20, verbose_name='Color de la Compañía'),
        ),
        migrations.AddField(
            model_name='company',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='billing.currency', verbose_name='Moneda Predeterminada'),
        ),
        migrations.AddField(
            model_name='company',
            name='currency_provider',
            field=models.CharField(blank=True, default='sunat', max_length=50, null=True, verbose_name='Proveedor de Moneda Extranjera'),
        ),
        migrations.AddField(
            model_name='company',
            name='invoice_term',
            field=models.TextField(blank=True, null=True, verbose_name='Términos y Condiciones de la Factura'),
        ),
        migrations.AddField(
            model_name='company',
            name='sunat_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Monto para SUNAT'),
        ),
        migrations.AddField(
            model_name='company',
            name='tax_calculation_rounding_method',
            field=models.CharField(choices=[('global', 'round_globally'), ('por linea', 'round_per_line')], default='round_globally', max_length=20, verbose_name='Método de Redondeo de Cálculo de Impuestos'),
        ),
        migrations.AddField(
            model_name='company',
            name='text_color',
            field=models.CharField(default='black', max_length=20, verbose_name='Color del Texto'),
        ),
        migrations.AddField(
            model_name='company',
            name='theme_color',
            field=models.CharField(default='light', max_length=20, verbose_name='Color del Tema'),
        ),
        migrations.AddField(
            model_name='company',
            name='theme_text_color',
            field=models.CharField(default='dark', max_length=20, verbose_name='Color del Texto del Tema'),
        ),
    ]
