# Generated by Django 5.2.7 on 2025-11-14 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_company_account_tax_periodicity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='name',
        ),
        migrations.RemoveField(
            model_name='company',
            name='vat',
        ),
    ]
