# Generated by Django 5.2.7 on 2025-11-24 22:01

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_alter_partner_document_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountPaymentTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccountPaymentTermLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.IntegerField(default=10)),
                ('days', models.IntegerField(default=0, help_text='Días después de la fecha de emisión')),
                ('day_of_the_month', models.IntegerField(blank=True, help_text='Día específico del mes', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('option', models.CharField(choices=[('day_after_invoice_date', 'Días después fecha factura'), ('after_invoice_month', 'Después del mes factura'), ('day_following_month', 'Día del mes siguiente'), ('day_current_month', 'Día del mes actual')], default='day_after_invoice_date', max_length=30)),
                ('value', models.CharField(choices=[('balance', 'Balance'), ('percent', 'Porcentaje'), ('fixed', 'Monto Fijo')], default='balance', max_length=10)),
                ('value_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='DetractionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('pse_code', models.CharField(max_length=10)),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='ElectronicInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_gravada', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_inafecta', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_exonerada', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_gratuita', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_anticipo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_igv', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_icbper', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_venta', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_total_origin', models.DecimalField(decimal_places=10, default=0, max_digits=18)),
                ('sent_json', models.JSONField(blank=True, null=True)),
                ('response_json', models.JSONField(blank=True, null=True)),
                ('consult_json', models.JSONField(blank=True, null=True)),
                ('save_changes', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GuideDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guide_number', models.CharField(max_length=20)),
                ('guide_type', models.CharField(default='09', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceSerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('series', models.CharField(max_length=4)),
                ('is_active', models.BooleanField(default=True)),
                ('manual', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('pse_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('billing_type', models.CharField(choices=[('0', 'Nubefact'), ('1', 'OdooFacturacion')], max_length=1)),
                ('api_url', models.URLField()),
                ('api_token', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('series', models.CharField(max_length=4)),
                ('send_auto_sunat', models.BooleanField(default=True)),
                ('send_auto_client', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RelatedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('series', models.CharField(max_length=4)),
                ('number', models.CharField(max_length=8)),
                ('reference', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SunatCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('catalog_type', models.CharField(choices=[('01', 'Catálogo 01 - Tipo de Documento'), ('51', 'Catálogo 51 - Tipo de Operación'), ('10', 'Catálogo 10 - Tipo de Afectación IGV'), ('09', 'Catálogo 09 - Tipo de Guía'), ('tribute', 'Tipo de Tributo'), ('note_type', 'Tipo de Nota'), ('currency', 'Moneda')], max_length=20)),
                ('pse_code', models.CharField(blank=True, max_length=10, null=True)),
                ('code_sunat', models.CharField(blank=True, max_length=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=100)),
                ('value', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('rounded_ebill', models.IntegerField(default=2)),
                ('rounded_ebill_line', models.IntegerField(default=6)),
                ('verify_amount_odoo', models.BooleanField(default=True)),
                ('required_onu', models.BooleanField(default=False)),
                ('comment_add_check', models.BooleanField(default=False)),
                ('invoice_origin_check', models.BooleanField(default=False)),
                ('bank_numbers', models.TextField(blank=True, null=True)),
                ('send_address', models.CharField(choices=[('street', 'Solo Dirección'), ('address_complete', 'Dirección Completa'), ('adress_complete_ubigeo', 'Dirección Completa con Ubigeo')], default='street', max_length=30)),
                ('send_multi_credits', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='accountmove',
            old_name='qr_code_url',
            new_name='qr_code',
        ),
        migrations.RenameField(
            model_name='accountmoveline',
            old_name='tax_ids',
            new_name='tax',
        ),
        migrations.RemoveField(
            model_name='accountmove',
            name='date_invoice',
        ),
        migrations.RemoveField(
            model_name='accountmove',
            name='pdf_attachment',
        ),
        migrations.RemoveField(
            model_name='accountmove',
            name='xml_attachment',
        ),
        migrations.AddField(
            model_name='accountmove',
            name='amount_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='accountmove',
            name='billing_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='accountmove',
            name='cdr_url_s3',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accountmove',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='billing.currency'),
        ),
        migrations.AddField(
            model_name='accountmove',
            name='currency_rate',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=18),
        ),
        migrations.AddField(
            model_name='accountmove',
            name='delete_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accountmove',
            name='detraction_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='accountmove',
            name='document_type',
            field=models.CharField(choices=[('dni', 'DNI'), ('ruc', 'RUC'), ('ce', 'Carnet de Extranjería'), ('pasaporte', 'Pasaporte'), ('otro', 'Otro')], default='dni', max_length=20),
        ),
        migrations.AddField(
            model_name='accountmove',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='accountmove',
            name='file_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='accountmove',
            name='hash_code',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='accountmove',
            name='invoice_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='accountmove',
            name='invoice_date_due',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accountmove',
            name='json_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accountmove',
            name='json_sent',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accountmove',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='accountmove',
            name='narration',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accountmove',
            name='pdf_url_s3',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accountmove',
            name='print_version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='accountmove',
            name='ref',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='accountmove',
            name='retention_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='accountmove',
            name='sunat_state',
            field=models.CharField(choices=[('0', 'Pendiente'), ('1', 'Aceptado'), ('2', 'Rechazado'), ('3', 'Error de Envío'), ('4', 'Pagado')], default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='accountmove',
            name='type',
            field=models.CharField(choices=[('out_invoice', 'Factura de Cliente'), ('out_refund', 'Nota de Crédito'), ('in_invoice', 'Factura de Proveedor'), ('in_refund', 'Nota de Débito de Proveedor')], default='out_invoice', max_length=20),
        ),
        migrations.AddField(
            model_name='accountmove',
            name='xml_url_s3',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accountmove',
            name='xml_version',
            field=models.FileField(blank=True, null=True, upload_to='invoices/xml/'),
        ),
        migrations.AddField(
            model_name='accountmoveline',
            name='advance_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advance_regularization_lines', to='billing.accountmove'),
        ),
        migrations.AddField(
            model_name='accountmoveline',
            name='icbper_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='accountmoveline',
            name='igv_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='accountmoveline',
            name='igv_amount_origin',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='accountmoveline',
            name='is_advance_regularization',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accountmoveline',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='accountmoveline',
            name='subtotal_origin',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='accountmoveline',
            name='sunat_product_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='accountmoveline',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='accountmoveline',
            name='total_origin',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='product',
            name='is_advance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='onu_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('product', 'Producto'), ('service', 'Servicio')], default='product', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='uom_code',
            field=models.CharField(choices=[('NIU', 'Unidad'), ('ZZ', 'Servicio')], default='NIU', max_length=5),
        ),
        migrations.AddField(
            model_name='salesubscription',
            name='invoicing_interval',
            field=models.CharField(choices=[('daily', 'Diario'), ('weekly', 'Semanal'), ('monthly', 'Mensual'), ('quarterly', 'Trimestral'), ('yearly', 'Anual')], default='monthly', max_length=20),
        ),
        migrations.AddField(
            model_name='salesubscription',
            name='next_invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tax',
            name='is_icbper',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='accountmove',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.salesubscription'),
        ),
        migrations.AlterField(
            model_name='company',
            name='currency',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='billing.currency', verbose_name='Moneda Predeterminada'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddIndex(
            model_name='salesubscription',
            index=models.Index(fields=['code'], name='billing_sal_code_687d45_idx'),
        ),
        migrations.AddIndex(
            model_name='salesubscription',
            index=models.Index(fields=['state'], name='billing_sal_state_65ba91_idx'),
        ),
        migrations.AddIndex(
            model_name='salesubscription',
            index=models.Index(fields=['next_invoice_date'], name='billing_sal_next_in_f5cbe9_idx'),
        ),
        migrations.AddField(
            model_name='accountpaymentterm',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.company'),
        ),
        migrations.AddField(
            model_name='accountmove',
            name='invoice_payment_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.accountpaymentterm'),
        ),
        migrations.AddField(
            model_name='accountpaymenttermline',
            name='payment_term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='billing.accountpaymentterm'),
        ),
        migrations.AddField(
            model_name='detractiontype',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.company'),
        ),
        migrations.AddField(
            model_name='accountmove',
            name='detraction_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.detractiontype'),
        ),
        migrations.AddField(
            model_name='electronicinvoice',
            name='invoice',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='einvoice', to='billing.accountmove'),
        ),
        migrations.AddField(
            model_name='guidedocument',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guide_documents', to='billing.accountmove'),
        ),
        migrations.AddField(
            model_name='invoiceserie',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.company'),
        ),
        migrations.AddField(
            model_name='invoiceserie',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.journal'),
        ),
        migrations.AddField(
            model_name='accountmove',
            name='serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.invoiceserie'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.company'),
        ),
        migrations.AddField(
            model_name='accountmove',
            name='detraction_payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detraction_invoices', to='billing.paymentmethod'),
        ),
        migrations.AddField(
            model_name='providerconfig',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.company'),
        ),
        migrations.AddField(
            model_name='relateddocument',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_documents', to='billing.accountmove'),
        ),
        migrations.AddIndex(
            model_name='sunatcatalog',
            index=models.Index(fields=['catalog_type', 'code'], name='billing_sun_catalog_f462a6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sunatcatalog',
            unique_together={('catalog_type', 'code')},
        ),
        migrations.AddField(
            model_name='relateddocument',
            name='document_type',
            field=models.ForeignKey(limit_choices_to={'catalog_type': '01'}, on_delete=django.db.models.deletion.PROTECT, to='billing.sunatcatalog'),
        ),
        migrations.AddField(
            model_name='accountmove',
            name='credit_note_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'catalog_type': 'note_type'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_notes', to='billing.sunatcatalog'),
        ),
        migrations.AddField(
            model_name='accountmove',
            name='debit_note_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'catalog_type': 'note_type'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debit_notes', to='billing.sunatcatalog'),
        ),
        migrations.AddField(
            model_name='accountmove',
            name='op_type_sunat',
            field=models.ForeignKey(blank=True, limit_choices_to={'catalog_type': '51'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_operation_type', to='billing.sunatcatalog'),
        ),
        migrations.AddField(
            model_name='accountmoveline',
            name='affectation_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'catalog_type': '10'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='billing.sunatcatalog'),
        ),
        migrations.AddField(
            model_name='tax',
            name='affectation_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'catalog_type': '10'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='taxes', to='billing.sunatcatalog'),
        ),
        migrations.AddField(
            model_name='tax',
            name='eb_tributes_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'catalog_type': 'tribute'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tribute_taxes', to='billing.sunatcatalog'),
        ),
        migrations.AddIndex(
            model_name='accountmove',
            index=models.Index(fields=['ref'], name='billing_acc_ref_276d14_idx'),
        ),
        migrations.AddIndex(
            model_name='accountmove',
            index=models.Index(fields=['invoice_date'], name='billing_acc_invoice_eb71a1_idx'),
        ),
        migrations.AddIndex(
            model_name='accountmove',
            index=models.Index(fields=['state'], name='billing_acc_state_b4f318_idx'),
        ),
        migrations.AddIndex(
            model_name='accountmove',
            index=models.Index(fields=['sunat_state'], name='billing_acc_sunat_s_d3d14a_idx'),
        ),
        migrations.AddField(
            model_name='systemparameter',
            name='advance_codes',
            field=models.ManyToManyField(blank=True, limit_choices_to={'catalog_type': '51'}, related_name='advance_parameters', to='billing.sunatcatalog'),
        ),
        migrations.AddField(
            model_name='systemparameter',
            name='advance_products',
            field=models.ManyToManyField(blank=True, related_name='advance_parameters', to='billing.product'),
        ),
        migrations.AddField(
            model_name='systemparameter',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.company'),
        ),
        migrations.AddField(
            model_name='systemparameter',
            name='detraction_codes',
            field=models.ManyToManyField(blank=True, limit_choices_to={'catalog_type': '51'}, related_name='detraction_parameters', to='billing.sunatcatalog'),
        ),
        migrations.AddField(
            model_name='systemparameter',
            name='igv_tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.tax'),
        ),
        migrations.AlterUniqueTogether(
            name='guidedocument',
            unique_together={('invoice', 'guide_number')},
        ),
        migrations.AlterUniqueTogether(
            name='providerconfig',
            unique_together={('company', 'series', 'billing_type')},
        ),
        migrations.AlterUniqueTogether(
            name='relateddocument',
            unique_together={('invoice', 'reference')},
        ),
        migrations.AlterUniqueTogether(
            name='systemparameter',
            unique_together={('company', 'key')},
        ),
    ]
