# Generated by Django 5.2.7 on 2025-11-24 23:17

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_accountpaymentterm_accountpaymenttermline_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salesubscription',
            name='invoices_generated',
            field=models.IntegerField(default=0, verbose_name='Facturas Generadas'),
        ),
        migrations.AddField(
            model_name='salesubscription',
            name='total_invoiced',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Total Facturado'),
        ),
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del Contrato')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('recurring_rule_type', models.CharField(choices=[('daily', 'Diario'), ('weekly', 'Semanal'), ('monthly', 'Mensual'), ('yearly', 'Anual')], default='monthly', max_length=20, verbose_name='Tipo de Recurrencia')),
                ('recurring_interval', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Intervalo de Recurrencia')),
                ('recurring_rule_boundary', models.CharField(choices=[('unlimited', 'Ilimitado'), ('limited', 'Limitado')], default='unlimited', max_length=20, verbose_name='Límite de Recurrencia')),
                ('recurring_rule_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Número de Repeticiones')),
                ('payment_mode', models.CharField(choices=[('manual', 'Manual'), ('draft_invoice', 'Borrador de Factura Automático'), ('validate_invoice', 'Factura Validada Automática')], default='manual', max_length=20, verbose_name='Modo de Facturación')),
                ('auto_close_limit', models.IntegerField(default=15, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Límite de Cierre Automático (días)')),
                ('user_closable', models.BooleanField(default=True, verbose_name='Usuario Puede Cerrar')),
                ('calculate_upsell', models.BooleanField(default=False, verbose_name='Calcular Upsell')),
                ('is_massive', models.BooleanField(default=False, verbose_name='Es Masivo')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_templates', to='billing.company', verbose_name='Compañía')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contract_templates', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_contract_templates', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado Por')),
            ],
            options={
                'verbose_name': 'Plantilla de Contrato',
                'verbose_name_plural': 'Plantillas de Contratos',
                'db_table': 'billing_contracttemplate',
            },
        ),
        migrations.AddField(
            model_name='salesubscription',
            name='contract_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.contracttemplate', verbose_name='Plantilla de Contrato'),
        ),
        migrations.AddIndex(
            model_name='salesubscription',
            index=models.Index(fields=['contract_template'], name='billing_sal_contrac_45dcec_idx'),
        ),
        migrations.AddIndex(
            model_name='contracttemplate',
            index=models.Index(fields=['active'], name='billing_con_active_ad078c_idx'),
        ),
        migrations.AddIndex(
            model_name='contracttemplate',
            index=models.Index(fields=['code'], name='billing_con_code_d2585a_idx'),
        ),
        migrations.AddIndex(
            model_name='contracttemplate',
            index=models.Index(fields=['is_massive'], name='billing_con_is_mass_fe798d_idx'),
        ),
    ]
