# Generated by Django 5.2.7 on 2025-11-24 23:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0008_salesubscription_invoices_generated_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="is_advance",
        ),
    ]
