# Generated by Django 5.2.7 on 2025-11-25 15:27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0009_remove_product_is_advance"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="Nombre")),
                (
                    "code",
                    models.CharField(
                        help_text="Código único para identificar la secuencia",
                        max_length=100,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "implementation",
                    models.CharField(
                        choices=[("standard", "Standard"), ("no_gap", "No Gap")],
                        default="standard",
                        max_length=20,
                        verbose_name="Implementación",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Activa")),
                (
                    "prefix",
                    models.CharField(
                        blank=True,
                        help_text="Ej: F001- para facturas",
                        max_length=50,
                        verbose_name="Prefijo",
                    ),
                ),
                (
                    "suffix",
                    models.CharField(blank=True, max_length=50, verbose_name="Sufijo"),
                ),
                (
                    "number_next",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Próximo Número",
                    ),
                ),
                (
                    "number_increment",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Incremento",
                    ),
                ),
                (
                    "padding",
                    models.IntegerField(
                        default=8,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Relleno de ceros",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sequences",
                        to="billing.company",
                        verbose_name="Compañía",
                    ),
                ),
            ],
            options={
                "verbose_name": "Secuencia",
                "verbose_name_plural": "Secuencias",
                "db_table": "billing_sequence",
            },
        ),
        migrations.AddField(
            model_name="invoiceserie",
            name="sequence",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoice_series",
                to="billing.sequence",
                verbose_name="Secuencia Asociada",
            ),
        ),
        migrations.AddIndex(
            model_name="sequence",
            index=models.Index(fields=["code"], name="billing_seq_code_064f5e_idx"),
        ),
        migrations.AddIndex(
            model_name="sequence",
            index=models.Index(
                fields=["company", "active"], name="billing_seq_company_de7fbe_idx"
            ),
        ),
    ]
