# Generated by Django 5.2.7 on 2025-11-25 20:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0011_alter_invoiceserie_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoiceserie",
            name="name",
            field=models.CharField(max_length=80),
        ),
    ]
