# Generated by Django 5.2.7 on 2025-11-26 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_alter_invoiceserie_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesubscription',
            name='code',
            field=models.CharField(blank=True, help_text='Código interno de la suscripción', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='salesubscription',
            name='company',
            field=models.ForeignKey(help_text='Compañía asociada a la suscripción', on_delete=django.db.models.deletion.PROTECT, to='billing.company'),
        ),
        migrations.AlterField(
            model_name='salesubscription',
            name='date_end',
            field=models.DateField(blank=True, help_text='Fecha de finalización del contrato', null=True),
        ),
        migrations.AlterField(
            model_name='salesubscription',
            name='date_start',
            field=models.DateField(help_text='Fecha de inicio del contrato'),
        ),
        migrations.AlterField(
            model_name='salesubscription',
            name='description',
            field=models.TextField(blank=True, help_text='Descripción de la suscripción', null=True),
        ),
        migrations.AlterField(
            model_name='salesubscription',
            name='health',
            field=models.CharField(default='normal', help_text='Estado de salud de la suscripción', max_length=20),
        ),
        migrations.AlterField(
            model_name='salesubscription',
            name='invoicing_interval',
            field=models.CharField(choices=[('daily', 'Diario'), ('weekly', 'Semanal'), ('monthly', 'Mensual'), ('quarterly', 'Trimestral'), ('yearly', 'Anual')], default='monthly', help_text='Intervalo de facturación', max_length=20),
        ),
        migrations.AlterField(
            model_name='salesubscription',
            name='next_invoice_date',
            field=models.DateField(blank=True, help_text='Próxima fecha programada para facturación', null=True),
        ),
        migrations.AlterField(
            model_name='salesubscription',
            name='partner',
            field=models.ForeignKey(help_text='Cliente asociado a la suscripción', on_delete=django.db.models.deletion.PROTECT, to='billing.partner'),
        ),
        migrations.AlterField(
            model_name='salesubscription',
            name='recurring_invoice_count',
            field=models.IntegerField(default=0, help_text='Número de facturas recurrentes generadas'),
        ),
        migrations.AlterField(
            model_name='salesubscription',
            name='recurring_invoice_day',
            field=models.IntegerField(default=1, help_text='Día del mes para facturación recurrente'),
        ),
        migrations.AlterField(
            model_name='salesubscription',
            name='recurring_monthly',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto mensual recurrente', max_digits=18),
        ),
        migrations.AlterField(
            model_name='salesubscription',
            name='recurring_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total recurrente del contrato', max_digits=18),
        ),
        migrations.AlterField(
            model_name='salesubscription',
            name='state',
            field=models.CharField(default='active', help_text='Estado de la suscripción', max_length=20),
        ),
        migrations.AlterField(
            model_name='salesubscription',
            name='to_renew',
            field=models.BooleanField(default=True, help_text='Indica si la suscripción debe renovarse automáticamente'),
        ),
        migrations.AlterField(
            model_name='salesubscription',
            name='uuid',
            field=models.CharField(help_text='Identificador único universal de la suscripción', max_length=64, unique=True),
        ),
        migrations.AddIndex(
            model_name='sequence',
            index=models.Index(fields=['company', 'code'], name='billing_seq_company_71a3b6_idx'),
        ),
    ]
