# Generated by Django 5.2.7 on 2025-11-26 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0013_alter_salesubscription_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesubscription",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Indica si la suscripción está activa"
            ),
        ),
    ]
