# Generated by Django 5.2.7 on 2025-12-01 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_accountmove_billing_acc_company_9fd468_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountpaymenttermline',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
