# Generated by Django 5.2.7 on 2025-12-01 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0017_accountpaymenttermline_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="contracttemplate",
            name="payment_term",
            field=models.ForeignKey(
                blank=True,
                help_text="Término de pago predeterminado para contratos con esta plantilla",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="billing.accountpaymentterm",
                verbose_name="Término de Pago por Defecto",
            ),
        ),
        migrations.AddField(
            model_name="partner",
            name="payment_term",
            field=models.ForeignKey(
                blank=True,
                help_text="Término de pago predeterminado para este cliente",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="billing.accountpaymentterm",
                verbose_name="Término de Pago por Defecto",
            ),
        ),
        migrations.AddField(
            model_name="salesubscription",
            name="payment_term",
            field=models.ForeignKey(
                blank=True,
                help_text="Término de pago específico para esta suscripción",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="billing.accountpaymentterm",
                verbose_name="Término de Pago",
            ),
        ),
        migrations.AlterField(
            model_name="accountmove",
            name="invoice_payment_term",
            field=models.ForeignKey(
                blank=True,
                help_text="Término de pago aplicado a esta factura",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="billing.accountpaymentterm",
                verbose_name="Término de Pago",
            ),
        ),
    ]
