# Generated by Django 5.2.9 on 2026-01-09 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0019_partner_invoice_end_of_month_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currencyrate',
            name='rate',
        ),
        migrations.AlterField(
            model_name='partner',
            name='num_document',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Número de Documento'),
        ),
    ]
