# Generated by Django 5.2.9 on 2026-01-12 22:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0020_remove_currencyrate_rate_alter_partner_num_document'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='ruc_condition',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='ruc_state',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='sunat_success',
        ),
        migrations.AddField(
            model_name='partner',
            name='sunat_address',
            field=models.TextField(blank=True, verbose_name='Dirección SUNAT'),
        ),
        migrations.AddField(
            model_name='partner',
            name='sunat_comment',
            field=models.TextField(blank=True, verbose_name='Observaciones SUNAT'),
        ),
        migrations.AddField(
            model_name='partner',
            name='sunat_last_check',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última verificación'),
        ),
        migrations.AddField(
            model_name='partner',
            name='sunat_ubigeo',
            field=models.CharField(blank=True, max_length=6, verbose_name='Ubigeo SUNAT'),
        ),
        migrations.AddField(
            model_name='partner',
            name='sunat_valid',
            field=models.BooleanField(default=False, verbose_name='Válido en SUNAT'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='sunat_condition',
            field=models.CharField(choices=[('HABIDO', 'Habido'), ('NO_HABIDO', 'No Habido'), ('NO_APLICA', 'No Aplica'), ('NO_VERIFICADO', 'No Verificado')], default='NO_VERIFICADO', max_length=20, verbose_name='Condición SUNAT'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='sunat_state',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('BAJA', 'Baja'), ('SUSPENDIDO', 'Suspendido'), ('NO_VERIFICADO', 'No Verificado')], default='NO_VERIFICADO', max_length=20, verbose_name='Estado SUNAT'),
        ),
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['sunat_valid'], name='billing_par_sunat_v_96d49d_idx'),
        ),
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['sunat_state'], name='billing_par_sunat_s_9d39e0_idx'),
        ),
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['sunat_last_check'], name='billing_par_sunat_l_d308ea_idx'),
        ),
    ]
