# Generated by Django 5.2.7 on 2025-11-05 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_result_fileprocess_error_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileprocess',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
