# Generated by Django 5.2.7 on 2025-11-05 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_fileprocess_processed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileprocess',
            old_name='error_message',
            new_name='message',
        ),
    ]
