# Generated by Django 5.2.7 on 2025-11-05 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_taskrecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskrecord',
            options={'ordering': ['-started_at']},
        ),
        migrations.AddField(
            model_name='taskrecord',
            name='fileprocess',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_records', to='core.fileprocess'),
        ),
        migrations.AddField(
            model_name='taskrecord',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='taskrecord',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('STARTED', 'Started'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure')], default='PENDING', max_length=20),
        ),
    ]
