# Generated by Django 5.2.7 on 2025-11-05 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_taskrecord_options_taskrecord_fileprocess_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskrecord',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='taskrecord',
            old_name='started_at',
            new_name='created_at',
        ),
    ]
